name: Python package

on:
  push:
    branches:
      - main  # or 'master', depending on your branch name
  pull_request:
    branches:
      - main  # or 'master', depending on your branch name

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12  # Specify Python 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: |
        pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile main.py

    - name: Upload Executable as Artifact
      uses: actions/upload-artifact@v4  # Update to v4
      with:
        name: my-build
        path: dist/
