name: Normal build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller  # Install PyInstaller for building

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller.exe --onefile --noconsole --add-data "asset;asset" main.py
          
      - name: Archive the output
        uses: actions/upload-artifact@v2  # Use version v2, as v3 may be deprecated
        with:
          name: build
          path: dist/main.exe
