name: Python package

on:
  push:
    branches:
      - main  # or 'master', depending on your branch name
  pull_request:
    branches:
      - main  # or 'master', depending on your branch name

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]  # List versions you want to support

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile main.py
      
    - name: Upload Executable as Artifact (Updated)
      uses: actions/upload-artifact@latest
      with:
        name: my-build
        path: dist/
